source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '8.0'

target 'ZZDebugTool_Example' do
  pod 'ZZDebugTool', :path => '../'

  target 'ZZDebugTool_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
